import { CustomerItem } from "./customerSlice";

export const customerData: CustomerItem[] = [
  {
    id: "dLKZlSvlh_7Ijf5L57vTl",
    name: "Juli Puspasari",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4139227,
  },
  {
    id: "-Dff0F1ef3_UXntLtdiEC",
    name: "Wirda Sihombing",
    level: "konglomerat",
    favorite_menu: "Sate Ayam",
    total_transaction: 3574058,
  },
  {
    id: "bP1x8PzA23w5trmm0xDlq",
    name: "T. Lega Lestari",
    level: "sultan",
    favorite_menu: "Steak Wagyu",
    total_transaction: 3793909,
  },
  {
    id: "QaZWiR-q42fzPgAl5eZnE",
    name: "Siska Adriansyah",
    level: "konglomerat",
    favorite_menu: "Soto Betawi",
    total_transaction: 2160830,
  },
  {
    id: "PCLnTak-9wFbm9Qt9Iaeq",
    name: "dr. Estiawan Manullang",
    level: "juragan",
    favorite_menu: "Bakso",
    total_transaction: 2301777,
  },
  {
    id: "MGauhDu2vnMDuLp3358qI",
    name: "Wadi Fujiati",
    level: "juragan",
    favorite_menu: "Mie Ayam",
    total_transaction: 1519377,
  },
  {
    id: "wh3FcjJ1-jdTDBloFbyCr",
    name: "dr. Keisha Hutagalung, M.Farm",
    level: "warga",
    favorite_menu: "Sate Ayam",
    total_transaction: 4701159,
  },
  {
    id: "6inouMkKoOnS0Oh8MeAxX",
    name: "Farhunnisa Saragih",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 2932688,
  },
  {
    id: "6q5KZIAVqQ_Z-3GMPB0Oy",
    name: "H. Gantar Simbolon",
    level: "sultan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4762964,
  },
  {
    id: "qH8y4T121nvLnGkVlCp5L",
    name: "Dt. Langgeng Andriani, S.Psi",
    level: "warga",
    favorite_menu: "Soto Betawi",
    total_transaction: 2137072,
  },
  {
    id: "5BT8socHnxq18OnSjE5ew",
    name: "Cakrabirawa Kurniawan",
    level: "warga",
    favorite_menu: "Bakso",
    total_transaction: 1623702,
  },
  {
    id: "edLbSzreXsLRI5YKMgMRj",
    name: "Hani Sirait, S.E.",
    level: "juragan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 912507,
  },
  {
    id: "wXpDRGI07_Mau1jNcQMa6",
    name: "Kayun Aryani",
    level: "sultan",
    favorite_menu: "Rendang",
    total_transaction: 4082083,
  },
  {
    id: "Dl8IZjUPplR_7ug71HYOp",
    name: "Prayitna Ramadan, S.Sos",
    level: "juragan",
    favorite_menu: "Mie Ayam",
    total_transaction: 2114942,
  },
  {
    id: "KQMZqyIUb1HnywCfbmBTm",
    name: "Dian Nasyiah, M.Pd",
    level: "sultan",
    favorite_menu: "Steak Wagyu",
    total_transaction: 2557206,
  },
  {
    id: "ZGSbmxLeDw2YfI3j1zfSl",
    name: "Dina Maryati",
    level: "konglomerat",
    favorite_menu: "Mie Ayam",
    total_transaction: 2738143,
  },
  {
    id: "JAl3pU6HGm-2uS44sfmuw",
    name: "Belinda Maryati",
    level: "konglomerat",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4534991,
  },
  {
    id: "zpiMHzrEmCE6U09m-EZVk",
    name: "Paiman Saptono, S.IP",
    level: "konglomerat",
    favorite_menu: "Nasi Goreng",
    total_transaction: 4623429,
  },
  {
    id: "qss7lO8nLBbF9WDhTEY5Y",
    name: "Gabriella Mardhiyah",
    level: "warga",
    favorite_menu: "Steak Wagyu",
    total_transaction: 745724,
  },
  {
    id: "wMY4zI0JxjWxPfUu_z8Ps",
    name: "Hilda Kuswandari",
    level: "warga",
    favorite_menu: "Soto Betawi",
    total_transaction: 1440114,
  },
  {
    id: "aOjCXBLzv4LeerJic9A0I",
    name: "R. Dariati Sitompul, S.T.",
    level: "sultan",
    favorite_menu: "Rendang",
    total_transaction: 2354915,
  },
  {
    id: "eTrn6ml_xWWp952dPAmQm",
    name: "Gawati Rahimah",
    level: "sultan",
    favorite_menu: "Steak Wagyu",
    total_transaction: 624848,
  },
  {
    id: "0BQnBtUb0ZLqQZcMHwpYU",
    name: "Hj. Paramita Pertiwi, S.I.Kom",
    level: "warga",
    favorite_menu: "Bakso",
    total_transaction: 4622877,
  },
  {
    id: "cTFPFImuhd7b1-kSZQoFD",
    name: "Kania Mulyani, S.Sos",
    level: "warga",
    favorite_menu: "Steak Wagyu",
    total_transaction: 2469490,
  },
  {
    id: "RbSUSBC4a_OnAraR6agWI",
    name: "Kamal Thamrin",
    level: "juragan",
    favorite_menu: "Sate Ayam",
    total_transaction: 3162132,
  },
  {
    id: "A9qS7i54qI7viurVi7MZy",
    name: "Ir. Padmi Hartati, S.Pt",
    level: "konglomerat",
    favorite_menu: "Soto Betawi",
    total_transaction: 542929,
  },
  {
    id: "H9ekEDqwXRba0-RM7V6cz",
    name: "Febi Uwais",
    level: "sultan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4996454,
  },
  {
    id: "mPkvAL_uY3Tt2bKbd7s8o",
    name: "drg. Uchita Wibisono, S.IP",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 1546247,
  },
  {
    id: "MiTfLWv8GWEXLCJ-XFUHd",
    name: "Marwata Mardhiyah",
    level: "juragan",
    favorite_menu: "Mie Ayam",
    total_transaction: 3727022,
  },
  {
    id: "1mFpazqD_3UOxywWpGS1q",
    name: "Maida Latupono",
    level: "juragan",
    favorite_menu: "Bakso",
    total_transaction: 1699221,
  },
  {
    id: "GkX8-wft3aHsBZqxzYq8c",
    name: "Ajimat Yolanda, S.Pd",
    level: "sultan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 1896292,
  },
  {
    id: "ggI7YeOoODGTIvi9J3e7n",
    name: "R.A. Pia Padmasari",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4974241,
  },
  {
    id: "ZUf6swE3vEn80nBvhX7px",
    name: "Belinda Hutagalung",
    level: "sultan",
    favorite_menu: "Sate Ayam",
    total_transaction: 268578,
  },
  {
    id: "hbDnOEfDCkN4XmlmfqX_v",
    name: "Ina Nurdiyanti",
    level: "juragan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 1539542,
  },
  {
    id: "dKUY6fUde51xHE5xhlTY1",
    name: "Puput Tamba",
    level: "juragan",
    favorite_menu: "Rendang",
    total_transaction: 686397,
  },
  {
    id: "vZXucpn_xzCpGkXBy0TSq",
    name: "Sutan Jayadi Prabowo",
    level: "konglomerat",
    favorite_menu: "Steak Wagyu",
    total_transaction: 252568,
  },
  {
    id: "tslZWfd13qUwt95GbCLFK",
    name: "Bella Wastuti",
    level: "juragan",
    favorite_menu: "Mie Ayam",
    total_transaction: 415309,
  },
  {
    id: "9a2bcd8ZmApho4JwKkpqZ",
    name: "Sabar Lazuardi",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 941912,
  },
  {
    id: "slNqsUJbzAQ7UKQTTYa6G",
    name: "Cut Tami Winarno",
    level: "sultan",
    favorite_menu: "Nasi Goreng",
    total_transaction: 4469845,
  },
  {
    id: "0QrnCa2CMZt2woN1jKAJ_",
    name: "Bambang Sinaga",
    level: "sultan",
    favorite_menu: "Soto Betawi",
    total_transaction: 4080804,
  },
  {
    id: "TCiRUCiJHg8BpvNwrscfs",
    name: "Olga Utami",
    level: "sultan",
    favorite_menu: "Sate Ayam",
    total_transaction: 4910221,
  },
  {
    id: "B1ILrpYSxrSU9tE2AEBrp",
    name: "Septi Maheswara",
    level: "sultan",
    favorite_menu: "Soto Betawi",
    total_transaction: 3355169,
  },
  {
    id: "frj9XrTIZAnznbhnI-ops",
    name: "Karma Sihombing",
    level: "juragan",
    favorite_menu: "Bakso",
    total_transaction: 4189192,
  },
  {
    id: "soBavtAieBIb4HRIWDAEm",
    name: "Karimah Wibowo, M.TI.",
    level: "sultan",
    favorite_menu: "Sate Ayam",
    total_transaction: 2725808,
  },
  {
    id: "ghXiYizKI4AqLYQENXv--",
    name: "drg. Gabriella Saragih",
    level: "warga",
    favorite_menu: "Ayam Geprek",
    total_transaction: 4681586,
  },
  {
    id: "9RcDUw7Jl8y0Wj9ImBi07",
    name: "Wawan Nainggolan",
    level: "sultan",
    favorite_menu: "Mie Ayam",
    total_transaction: 4600629,
  },
  {
    id: "myahuNXWI5lOGKkowAP8U",
    name: "Putri Hasanah, S.T.",
    level: "sultan",
    favorite_menu: "Sate Ayam",
    total_transaction: 3965691,
  },
  {
    id: "hf4JiAwcsXnCItiKr04P8",
    name: "Bakti Mustofa",
    level: "warga",
    favorite_menu: "Nasi Goreng",
    total_transaction: 4401641,
  },
  {
    id: "K0XwnoFjqxAEMJvzHfPpC",
    name: "Elvina Najmudin",
    level: "konglomerat",
    favorite_menu: "Mie Ayam",
    total_transaction: 4098834,
  },
  {
    id: "VzYaFOTUbyCZJ9LqNiRdY",
    name: "Galar Gunawan",
    level: "sultan",
    favorite_menu: "Ayam Geprek",
    total_transaction: 1443195,
  },
];
